export const dummyCategories = [
  ["인간관계(친목)", "HUMAN_RELATIONSHIP"],
  ["술", "ALCOHOL"],
  ["자기계발/공부", "SELF_IMPROVEMENT"],
  ["예술", "ART"],
  ["스포츠/운동", "SPORTS"],
  ["음식", "FOOD"],
  ["라이프", "LIFE"],
  ["공예/만들기", "CRAFT"],
  ["책/글쓰기/독서", "BOOK"],
  ["차/음료", "TEE"],
  ["커리어/직장", "CAREER"],
  ["재테크", "REINVESTMENT"],
  ["반려동물", "PET"],
  ["게임/액티비티", "GAME"],
  ["여행", "TRAVEL"],
  ["심리/상담", "PSYCHOLOGY"],
  ["인테리어/가구", "INTERIOR"],
  ["건강", "HEALTH"],
  ["환경", "ENVIRONMENT"],
  ["미용", "BEAUTY"],
  ["트렌드", "TREND"],
  ["연애/이성관계", "LOVE"],
  ["식물/자연", "PLANT"],
];
